### ISSUE TITLE
Does not work on Arch Linux

### ISSUE THREAD

**Issue by VoyTechnology** [ivanceras/machine-ip#1]
When running on Arch Linux it fails:

Snippet:
```rust
let local_addr = machine_ip::get().unwrap();
```

Error:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
```

I looks like `hostname -i` works fine, but only on Arch. On Ubuntu it returns `127.0.1.1`

**Comment by ivanceras** [comment]
I'm not sure if it's possible in rust to detect platform specific, so archlinux can have a different code branch to use `hostname -i`. I bet the truly cross-platform way of doing this would be to call the equivalent function from libc, just like what https://github.com/fengcen/hostname did. I still have to do experiment and research on libc though.

**Comment by ivanceras** [comment]
Hi @VoyTechnology, I just realized that the implementation is wrong if `hostname -i` returns 2 ip addresses. This now parse correctly and return the first ip, which is the useful ip in LAN connection.

I'm positive this should work on your usecase by now, let me know if it doesn't
