### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by NealEhardt** [ivanceras/machine-ip#3]
On Windows 10, the `stdout` string is empty [here](https://github.com/ivanceras/machine-ip/blob/master/src/lib.rs#L12). That causes `machine_ip::get()` to return None.

I don't think that this crate should support Windows - there doesn't seem to be an equivalent command to `hostname -I`.

If you could, please update README.md to say that it doesn't work on Windows.

**Comment by ivanceras** [comment]
Yep thanks.
